#!/usr/bin/env perl

use warnings "all";

# Simple preprocessor to fix @ASM directives in z.mlp and z.mlip, and
# generate z.ml and z.mli

# This file is part of the Zarith library
# http://forge.ocamlcore.org/projects/zarith .
# It is distributed under LGPL 2 licensing, with static linking exception.
# See the LICENSE file included in the distribution.
#
# Copyright (c) 2010-2011 Antoine Miné, Abstraction project.
# Abstraction is part of the LIENS (Laboratoire d'Informatique de l'ENS),
# a joint laboratory by:
# CNRS (Centre national de la recherche scientifique, France),
# ENS (École normale supérieure, Paris, France),
# INRIA Rocquencourt (Institut national de recherche en informatique, France).


die "Usage: './z_pp.pl architecture'" unless $#ARGV==0;

# version, from META file

$v = `grep version META`;
($ver) = $v =~ /version\s*=\s*(\S+)/;

$ov = `ocamlc -version`;
($major,$minor,$extra) = split(/\./, $ov, 3);

# specialize .ml & .mli files

sub doml {
    $SUF = shift @_;
    open I, "<z.${SUF}p";
    open O, ">z.${SUF}";
    print O "(* This file was automatically generated by z_pp.pl from z.${SUF}p *)  ";
    while (defined($l = <I>)) {
        $l =~ s/\@VERSION/$ver/;
        print O "$l";
    }
    close F;
}

doml "ml";
doml "mli";

